name: Deploying
on:
  push:
    branches:
      - master
  release:
    types: [created]
jobs:
  versionjob:
    name: Get Version
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: version as per event
        run: |
        if: github.event_name == 'push'
         echo "::set-output name=VERSION::$(date +'%Y.%-m.%-d')"
        if: github.event_name == 'release'
         echo "::set-output name=VERSION::$(git describe --tags `git rev-list --tags --max-count=1`)"
    outputs:
     versiontext: ${{ steps.dateversion.outputs.VERSION }}
  version-update:
    name: Version increment
    runs-on: macOS-latest
    needs: [versionjob]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: Get version from releases
        run: |
          echo "::set-output name=LATEST_TAG_NUMBER::$(git describe --tags `git rev-list --tags --max-count=1`)"
        id: dateversion
      - name: Get commits count
        run: |
          echo "::set-output name=GIT_COMMIT_NUMBER::$(git rev-list --count HEAD)"
        id: commits
      - name: Set version and build number
        run: |
          echo "version=${{needs.versionjob.outputs.versiontext}}"
