name: Deploying
on:
  push:
    branches:
      - master
  release:
    types: [created]
jobs:
  version-update:
    if: github.event_name == 'push'
    name: Version increment
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: Get version from date
        run: |
          echo "::set-output name=VERSION::$(date +'%Y.%-m.%-d')"
          echo "Version code after empty commit is $((date+24*60*60) +'%Y-%-m-%-d')"
        id: dateversion
      - name: Get commits count
        run: |
          echo "::set-output name=GIT_COMMIT_NUMBER::$(git rev-list --count HEAD)"
        id: commits
  
