name: Deploying
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Get current date
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY.M.DD
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: Get commits count
        run: |
          echo "::set-output name=GIT_COMMIT_NUMBER::$(git rev-list --count master)"
        id: commits
      - name: print
        run: |
          echo "${{steps.commits.outputs.GIT_COMMIT_NUMBER}}"
      - name: Set Version and Build number
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{steps.current-time.outputs.formattedTime}}
          project-path: ./mindLAMP.xcodeproj
      - name: update
        run: |
          git add .
          git commit -m "bump version"
          git push origin HEAD
      - name: Install gpg 
        run: brew install gpg
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: .github/secrets/decrypt_secrets.sh
      - name: Archiving project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: .github/scripts/archive_app.sh
      - name: Exporting .ipa
        run: .github/scripts/export_ipa.sh
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: .github/scripts/publish_testflight.sh