name: Deploying
on:
  push:
    branches:
      - master
  release:
    types: [created]
jobs:
  push_deploy_staging:
    if: github.event_name == 'push'
    name: Deploying to Testflight for Staging
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: Get version from date
        run: |
          echo "VERSION=$(date +'%Y.%-m.%-d')" >> $GITHUB_OUTPUT
        id: dateversion
      - name: Get commits count
        run: |
          echo "GIT_COMMIT_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
        id: commits
      - name: Set version and build number
        run: |
          agvtool new-marketing-version ${{steps.dateversion.outputs.VERSION}}
          agvtool new-version -all ${{steps.commits.outputs.GIT_COMMIT_NUMBER}}
      - name: Setup provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          BUILD_PROVISION_PROFILE1_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE1_BASE64 }}
          BUILD_PROVISION_PROFILE2_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE2_BASE64 }}
          BUILD_PROVISION_PROFILE3_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE3_BASE64 }}
          BUILD_PROVISION_PROFILE4_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE4_BASE64 }}
          BUILD_PROVISION_PROFILE5_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE5_BASE64 }}
          BUILD_PROVISION_PROFILE6_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE6_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: .github/scripts/import_certificate_profiles.sh
      - name: Build Test
        run: .github/scripts/test_project.sh
      - name: Archiving project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: .github/scripts/archive_staging_app.sh
      - name: Exporting .ipa
        run: .github/scripts/export_ipa.sh
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_API_KEY_BASE64: ${{ secrets.APPSTORE_API_KEY_BASE64 }}
          APPSTORE_API_KEY_FILENAME: ${{ secrets.APPSTORE_API_KEY_FILENAME }}
        run: .github/scripts/publish_testflight.sh
  release_deploy_production:
    if: github.event_name == 'release'
    name: Deploying to Testflight for Production
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: Get latest tag
        run: |
          echo "::set-output name=LATEST_TAG_NUMBER::$(git describe --tags `git rev-list --tags --max-count=1`)"
        id: tags
      - name: Get commits count
        run: |
          echo "::set-output name=GIT_COMMIT_NUMBER::$(git rev-list --count HEAD)"
        id: commits
      - name: Set version and build number
        run: |
          agvtool new-marketing-version ${{steps.tags.outputs.LATEST_TAG_NUMBER}}
          agvtool new-version -all ${{steps.commits.outputs.GIT_COMMIT_NUMBER}}
      - name: Setup provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          BUILD_PROVISION_PROFILE1_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE1_BASE64 }}
          BUILD_PROVISION_PROFILE2_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE2_BASE64 }}
          BUILD_PROVISION_PROFILE3_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE3_BASE64 }}
          BUILD_PROVISION_PROFILE4_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE4_BASE64 }}
          BUILD_PROVISION_PROFILE5_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE5_BASE64 }}
          BUILD_PROVISION_PROFILE6_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE6_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: .github/scripts/import_certificate_profiles.sh
      - name: Archiving project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: .github/scripts/archive_production_app.sh
      - name: Exporting .ipa
        run: .github/scripts/export_ipa.sh
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_API_KEY_BASE64: ${{ secrets.APPSTORE_API_KEY_BASE64 }}
          APPSTORE_API_KEY_FILENAME: ${{ secrets.APPSTORE_API_KEY_FILENAME }}
        run: .github/scripts/publish_testflight.sh
  version-update:
    if: github.event_name == 'release'
    name: Version increment
    runs-on: macos-latest
    needs: [release_deploy_production]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: Get version from releases
        run: |
          echo "::set-output name=LATEST_TAG_NUMBER::$(git describe --tags `git rev-list --tags --max-count=1`)"
        id: tagversion
      - name: Get commits count
        run: |
          echo "::set-output name=GIT_COMMIT_NUMBER::$(git rev-list --count HEAD)"
        id: commits
      - name: Set version and build number
        run: |
          agvtool new-marketing-version ${{steps.tagversion.outputs.LATEST_TAG_NUMBER}}
          agvtool new-version -all ${{steps.commits.outputs.GIT_COMMIT_NUMBER}}
      - name: update
        run: |
          git add .
          git commit -m "bump version"
          git push origin HEAD:master
