name: Deploying
on:
  push:
    branches:
      - master
  release:
    types: [created]
jobs:
  versionjob:
    name: Get Version
    if: github.event_name == 'push'
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: version as date
        run: |
         echo "::set-output name=VERSION::$(date +'%Y.%-m.%-d')"
        id: dateversion
    outputs:
     versiontext: ${{ steps.dateversion.outputs.VERSION }}
  versionjob2:
    name: Get Version
    if: github.event_name == 'release'
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: version as date
        id: dateversion
        run: |
         echo "::set-output name=VERSION::$(git describe --tags `git rev-list --tags --max-count=1`)"
    outputs:
     versiontext: ${{ steps.dateversion.outputs.VERSION }}
  version-update:
    name: Version increment
    runs-on: macOS-latest
    if: ${{ always() }}
    needs: [versionjob, versionjob2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: Get version from releases
        run: |
          echo "::set-output name=LATEST_TAG_NUMBER::$(git describe --tags `git rev-list --tags --max-count=1`)"
        id: tagversion
      - name: Get commits count
        run: |
          echo "::set-output name=GIT_COMMIT_NUMBER::$(git rev-list --count HEAD)"
        id: commits
      - name: Set version and build number
        run: |
          echo "version= ${{ format('{0}{1}.', needs.versionjob.outputs.versiontext, needs.versionjob2.outputs.versiontext }}"
