name: Deploying
on:
  push:
    branches:
      - Development
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Get current date
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY.M.DD
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: Get commits count
        run: |
          echo "::set-output name=GIT_COMMIT_NUMBER::$(git rev-list --count HEAD)"
        id: commits
      - name: Set Version and Build number
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ steps.current-time.outputs.formattedTime }}
          build-number: ${{ steps.commits.outputs.GIT_COMMIT_NUMBER }}
          project-path: mindLAMP.xcodeproj
      - name: Git push
        run: |
          git add .
          git commit -m "bump version"
          git push origin HEAD