name: Deploying
on:
  push:
    branches:
      - Development
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY.M.DD
      - name: Checkout repository
        uses: actions/checkout@v2
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ steps.current-time.outputs.formattedTime }}
          build-number: ${{ git rev-list --count master }}
      - name: update
        run: |
          git add .
          git commit -m "bump version"
          git push origin HEAD