name: Deploying
on:
  push:
    branches:
      - Development
jobs:
  deploy:
    name: Development Test
    runs-on: macOS-latest
    steps:
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY.M.DD
      - name: Use current time
        env:
          DATE: "${{ steps.current-time.outputs.formattedTime }}"	
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKENN }}
      - uses: yanamura/ios-bump-version@v1
        with:
          version: $DATE
          build-number: $GITHUB_RUN_NUMBER
      - name: update
        run: |
          git add .
          git commit -m "bump version"
          git push origin Development