name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app && /usr/bin/xcodebuild -version
      - name: Build Archive
        run: |
          xcodebuild -sdk iphoneos -project mindLAMP.xcodeproj \
            -configuration Release -scheme mindLAMP \
            -derivedDataPath DerivedData \
            -archivePath DerivedData/Archive/mindLAMP archive
      - name: Export Archive
        run: |
          xcodebuild -exportArchive \
            -archivePath DerivedData/Archive/mindLAMP.xcarchive \
            -exportOptionsPlist archive-export.plist \
            -allowProvisioningUpdates \
            -exportPath DerivedData/ipa
      - uses: actions/create-release@latest
        env:
          # this token is provided by github actions; do not create your own token:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Updates
          draft: false
          prerelease: false
